### ISSUE TITLE
Обработка текста через collections.Counter

### ISSUE THREAD

**Issue by zcho** [apalevich/PyMentor#10]
Сейчас слова в разных регистрах считаются как разные, нужно все слова в тексте привести к нижнему регистру, этим мы повысим точность подсчета.

Далее решить задачу с отбором часто встречающихся слов через ```collections.Counter```

https://docs.python.org/3/library/collections.html#collections.Counter

В отдельном файле.

**Comment by apalevich** [comment]
Что ты имеешь в виду - в отдельном файле? Перенести в новый файл .py весь код и доработать или написать там функцию, которая принимает dict в качестве аргумента?

**Comment by zcho** [comment]
Задачу по Counter в отдельном файле сделать.

**Comment by apalevich** [comment]
Сделал подсчёт через `collections.Counter` в файле `counter.py`

Функция работает, но ещё не разобрался с доктестом - ругается на символ экранирования `\`, при двойном экранировании выдаёт ошибку.

**Comment by apalevich** [comment]
Заменил экранирование на запятую. Функция работает, доктесты проходят
