### ISSUE TITLE
Разбор строки с командами

### ISSUE THREAD

**Issue by zcho** [apalevich/PyMentor#11]
Написать функцию
def parse_command(cmd:str) -> dict:

parse_command('add gazp 100')
вернуть {'action': 'add', 'instrument': 'gazp', 'value': 100)

parse_command('add gazp 100 150')
вернуть {'action': 'add', 'instrument': 'gazp', 'value': 100, 'value2': 150)

parse_command('add gazp 100-150')
вернуть {'action': 'add', 'instrument': 'gazp', 'value': 100, 'value2': 150)

parse_command('add gazp')
вернуть raise Exception('Укажите значение цены')

parse_command('add gazp asdf')
вернуть raise Exception('Значение должно быть числом')

parse_command('add gazp asdf 1')
вернуть raise Exception('Значение должно быть числом')

**Comment by apalevich** [comment]
Готово, в файле `parse_command.py` есть соответствующие проверки в доктесте
