### ISSUE TITLE
Задача про собак.

### ISSUE THREAD

**Issue by zcho** [apalevich/PyMentor#12]
Описать в виде класса собаку (Dog).
У него должны быть следующие свойства:
имя, дата рождения, голос

Создать 2-а экземпляра класса Dog со следующими параметрами
"Бобик", 1 января 2017, 'тяв-тяв'
"Тяпа", 2 января 2016, 'гав-гав'

Добавить возможность производить щенков следующим образом
```
puppy = boy_dog + girl_dog

Который в результате даёт:

puppy.voice()
# т.е. должно возвратить голоса М и Ж собак
>>> 'тяв-тяв гав-гав'

puppy.name()
>>> 'Щенок от собак Бобик и Тяпа'

puppy.birth_date()
# должно возвратить дату от рождения первой собаки родителя  + 480 дней.
```

**Comment by apalevich** [comment]
Готово https://github.com/apalevich/PyMentor/blob/master/06_dogs.py
