### ISSUE TITLE
Доработать класс ChatUser

### ISSUE THREAD

**Issue by zcho** [apalevich/PyMentor#16]
Нужно расширить класс ChatUser для решения следующую задачу:
1. У пользователя есть Имя Фамилия и Username, нужно их добавить в класс.
2. Если триал истёк, и пользователь не оплатил, то пользователь выключается.
3. За 3, 2, 1 день до конца триала нужно присылать ему уведомление о том что триал истекает, с предложением оплатить.
4. У оплаты есть срок, когда срок оплаты подходит к концу нужно слать уведомления за 3,2 1 день.

**Comment by apalevich** [comment]
Готово, см докстринг
https://github.com/apalevich/PyMentor/blob/master/09_trial_period.py
