### ISSUE TITLE
Сделать абстрактную функцию

### ISSUE THREAD

**Issue by zcho** [apalevich/PyMentor#6]
https://github.com/apalevich/PyMentor/blob/25430859407bd753e607fb02c5c1b021356d2103/text_analyzer.py#L72-L102

Эти две функции очень идентичны.
Хорошим стилем будет сделать из них одну (абстрагировать), с более общим именем.

**Comment by apalevich** [comment]
Хорошо, беру в работу

**Comment by apalevich** [comment]
Done, check please
