### ISSUE TITLE
Статистика по тексту.

### ISSUE THREAD

**Issue by zcho** [apalevich/PyMentor#7]
1. Читать входной текст из текстового файла.
2. Скачать в проект в директорию data вот этот файл и загрузить из него stop_words
```https://github.com/Alir3z4/stop-words/blob/bd8cc1434faeb3449735ed570a4a392ab5d35291/russian.txt```
3. Удалить из текста stop_words, что бы они не участвовали в статистике.
3. Кроме имеющейся информации, выдавать статистику по частоте вхождения в текст каждого слова - самые частые слова сначала.

**Comment by apalevich** [comment]
Я ещё не работал с файлами, пойду почитаю про это и сделаю

**Comment by apalevich** [comment]
Готово, смотри файл exclude_stopwords.py в репозитории
