### ISSUE TITLE
Проблема с открытием файлов

### ISSUE THREAD

**Issue by zcho** [apalevich/PyMentor#8]
https://github.com/apalevich/PyMentor/blob/310c77944d6c68462bcc38966fcaa3e46e50e26a/exclude_stopwords.py#L11

Проблема в том что файл открывается но не закрывается.
Прочитать:
```
It is good practice to use the with keyword when dealing with file objects
```
https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

**Comment by apalevich** [comment]
Переписал с использованием `with`, должно решить проблему с закрытием файлов
