### ISSUE TITLE
Не нужно сохранять файл и переоткрывать urllib.request

### ISSUE THREAD

**Issue by zcho** [apalevich/PyMentor#9]
https://github.com/apalevich/PyMentor/blob/310c77944d6c68462bcc38966fcaa3e46e50e26a/exclude_stopwords.py#L18-L24

Прочитать, есть готовый пример:

https://docs.python.org/3/tutorial/stdlib.html#internet-access

**Comment by apalevich** [comment]
Заменил модуль requests на urllib.request, стало лучше работать на windows
